networks:
  d2ray_br:
    external: false

services:
  d2ray:
    image: quackerd/d2ray
    container_name: d2ray
    ports:
      - 8443:8443
    environment:
      - PORT=8443
      - TARGET_URL=example.com
      - TARGET_PORT=443
      - USERS=exampleuser1,exampleuser2
      - LOG_LEVEL=warn
    restart: unless-stopped
    networks:
      - d2ray_br
    volumes:
      - ./config:/etc/d2ray
