networks:
  d2ray_br:
    external: false

services:
  d2ray:
    image: quackerd/d2ray
    container_name: d2ray
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - TARGET_URL=${TARGET_URL}
      - TARGET_PORT=${TARGET_PORT}
      - USERS=${USERS}
      - LOG_LEVEL=${LOG_LEVEL}
    restart: unless-stopped
    networks:
      - d2ray_br
    volumes:
      - ./config:/etc/d2ray
